In [23]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/customer/customer (1).csv


In [22]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

df = pd.read_csv('/kaggle/input/customer/customer (1).csv')

data = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Green', 'Red']})

encoder = OrdinalEncoder()
encoded = encoder.fit_transform(data)
print(encoded)


[[2.]
 [1.]
 [0.]
 [1.]
 [2.]]


In [24]:
df=df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [25]:
import pandas as pd

df = pd.read_csv('/kaggle/input/customer/customer (1).csv')

print(df.columns)



Index(['age', 'gender', 'review', 'education', 'purchased'], dtype='object')


In [2]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("/kaggle/input/customer/customer (1).csv")

X = df[['review', 'education']]
y = df['purchased']

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.20, random_state=2)

oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])
X_train_encoded = oe.fit_transform(X_train)
X_test_encoded = oe.transform(X_test)

le = LabelEncoder()
Y_train_encoded = le.fit_transform(Y_train)
Y_test_encoded = le.transform(Y_test)

X_train_encoded[:5], Y_train_encoded[:5]


(array([[1., 2.],
        [2., 1.],
        [0., 1.],
        [0., 0.],
        [0., 2.]]),
 array([1, 1, 1, 0, 0]))

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv("/kaggle/input/customer/customer (1).csv")

df_encoded = pd.get_dummies(df, columns=['gender', 'review', 'education'], drop_first=True)

X = df_encoded.drop('purchased', axis=1)
y = df_encoded['purchased']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print(X_train.head())


    age  gender_Male  review_Good  review_Poor  education_School  education_UG
32   92         True        False        False             False          True
39   76         True        False         True             False         False
21   32         True        False        False             False         False
36   34        False         True        False             False          True
19   97         True        False         True             False         False


In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(Y_train)

print(le.classes_)

Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)
print(Y_train)


['No' 'Yes']
[1 1 1 0 0 1 1 0 0 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 1 0
 1 0 0]


In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

print("Encoded target:", y_train_encoded[:5])


Encoded target: [1 0 0 1 1]


In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression()
model.fit(X_train, y_train_encoded)

# Predict
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test_encoded, y_pred))


Accuracy: 0.4


In [11]:
Y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0])

In [12]:
X_train

age  gender_Male  review_Good  review_Poor  education_School  education_UG
32   92         True        False        False             False          True
39   76         True        False         True             False         False
21   32         True        False        False             False         False
36   34        False         True        False             False          True
19   97         True        False         True             False         False
42   30        False         True        False             False         False
49   25        False         True        False             False          True
26   53        False        False         True             False         False
22   18        False        False         True             False         False
13   57        False        False        False              True         False
41   23         True         True        False             False         False
17   22        False        False         True             False          True
45   61         True        False         True             False         False
24   16        False        False        False             False         False
23   96        False         True        False              True         False
4    16        False        False        False             False          True
33   89        False         True        False             False         False
14   15         True        False         True             False         False
30   73         True        False        False             False          True
10   98        False         True        False             False          True
28   48         True        False         True              True         False
44   77        False        False        False             False          True
34   86         True        False        False              True         False
18   19         True         True        False              True         False
20   57        False        False        False              True         False
25   57        False         True        False              True         False
6    18         True         True        False              True         False
7    60        False        False         True              True         False
47   38        False         True        False             False         False
1    68        False        False         True             False          True
16   59         True        False         True             False          True
0    30        False        False        False              True         False
15   75         True        False         True             False          True
5    31        False        False        False              True         False
11   74         True         True        False             False          True
9    74         True         True        False             False          True
8    65        False        False        False             False          True
12   51         True        False         True              True         False
43   27         True        False         True             False         False
37   94         True        False        False             False         False

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(Y_train)

Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

print(Y_train)


[1 1 1 0 0 1 1 0 0 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 1 0
 1 0 0]


In [14]:
import pandas as pd

df = pd.DataFrame({
    'color': ['red', 'blue', 'green'],
    'size': ['S', 'M', 'L']
})

numerics = pd.get_dummies(df, columns=['color', 'size'])

print(numerics)


   color_blue  color_green  color_red  size_L  size_M  size_S
0       False        False       True   False   False    True
1        True        False      False   False    True   False
2       False         True      False    True   False   False


In [16]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df = pd.DataFrame({
    'color': ['red', 'blue', 'green'],
    'size': ['S', 'M', 'L']
})

features = df[['color', 'size']]

encoder = OneHotEncoder(drop='first', sparse_output=False)

encoded = encoder.fit_transform(features).astype(int)

print(encoded)

feature_names = encoder.get_feature_names_out(['color', 'size'])
encoded_df = pd.DataFrame(encoded, columns=feature_names)
print(encoded_df)

[[0 1 0 1]
 [0 0 1 0]
 [1 0 0 0]]
   color_green  color_red  size_M  size_S
0            0          1       0       1
1            0          0       1       0
2            1          0       0       0
